name = "OrthancTools"
uuid = "d6a53a69-57dd-4bf1-83cc-71c4a7042fcf"
authors = ["Dale-Black <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
"HTTP" = "1.10"
"JSON" = "0.21"
"OrderedCollections" = "1.7"
"Downloads" = "1.6"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
